
begin
  
  --1 этап
  update UBRR_DATA.UBRR_RKO_COM_TYPES
    set  UBRR_DATA.UBRR_RKO_COM_TYPES.TARIF_USED_UNIQUE = 1,
         UBRR_DATA.UBRR_RKO_COM_TYPES.IDSMR_USED = '1,2,10'
   where UBRR_DATA.UBRR_RKO_COM_TYPES.COM_TYPE in ('SENCASH','RKO','RKBP','RKBK','R_IB','PP6','PP9',
                              '017','018', 'PP3', /*'PP3E',*/ 'UL_FL','UL_FL_VB', 'IP_DOH','IP_DOH_VB') ;
          
  update UBRR_DATA.UBRR_RKO_COM_TYPES
    set  UBRR_DATA.UBRR_RKO_COM_TYPES.MODIFY_FREQ_UNIQUE = 0
   where UBRR_DATA.UBRR_RKO_COM_TYPES.COM_TYPE in ('SENCASH','RKBP','RKBK','RKO','R_IB');

  update UBRR_DATA.UBRR_RKO_COM_TYPES
    set  UBRR_DATA.UBRR_RKO_COM_TYPES.MODIFY_FREQ_UNIQUE = 1
   where UBRR_DATA.UBRR_RKO_COM_TYPES.COM_TYPE in ('PP6','PP9',
                              '017','018', 'PP3',/* 'PP3E',*/ 'UL_FL','UL_FL_VB', 'IP_DOH','IP_DOH_VB') ;

  commit;
  
  --2 этап
  update UBRR_DATA.UBRR_RKO_COM_TYPES
    set  UBRR_DATA.UBRR_RKO_COM_TYPES.TARIF_USED_UNIQUE = 1,
         UBRR_DATA.UBRR_RKO_COM_TYPES.MODIFY_FREQ_UNIQUE = 1,
         UBRR_DATA.UBRR_RKO_COM_TYPES.IDSMR_USED = '1,2,10'
   where UBRR_DATA.UBRR_RKO_COM_TYPES.COM_TYPE in ('CASS_LIM_IP','CASS_LIM_UR');

  update UBRR_DATA.UBRR_RKO_COM_TYPES
    set  UBRR_DATA.UBRR_RKO_COM_TYPES.TARIF_USED_UNIQUE = 1,
         UBRR_DATA.UBRR_RKO_COM_TYPES.MODIFY_FREQ_UNIQUE = 0,
         UBRR_DATA.UBRR_RKO_COM_TYPES.IDSMR_USED = '1,2,10'
   where UBRR_DATA.UBRR_RKO_COM_TYPES.COM_TYPE in ('CASS_OTHER_IP','CASS_OTHER_UR');   

  commit;
  
  --3 этап
  update UBRR_DATA.UBRR_RKO_COM_TYPES
    set  UBRR_DATA.UBRR_RKO_COM_TYPES.TARIF_USED_UNIQUE = 1,
         UBRR_DATA.UBRR_RKO_COM_TYPES.MODIFY_FREQ_UNIQUE = 1,
         UBRR_DATA.UBRR_RKO_COM_TYPES.IDSMR_USED = '1,2,10'
   where UBRR_DATA.UBRR_RKO_COM_TYPES.COM_TYPE in ('VZN');

  commit;    

exception 
  when others then
     rollback;
end;                              
/
